# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    # TODO: wraps postgres and put initialization scripts in
    image: edlam711/postgres
    # restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
